apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-tracker-backend
  namespace: progress-tracker
  labels:
    app: progress-tracker
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: progress-tracker
      tier: backend
  template:
    metadata:
      labels:
        app: progress-tracker
        tier: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/progress-tracker-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: progress-tracker-config
              key: gcp.project.id
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: progress-tracker-secrets
              key: jwt-secret
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: progress-tracker-secrets
              key: gemini-api-key
        - name: EMAIL_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: progress-tracker-config
              key: email.service.url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: progress-tracker
spec:
  selector:
    app: progress-tracker
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: progress-tracker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: progress-tracker-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
